### ISSUE TITLE
Improvement: add details of executed processes to log

### ISSUE THREAD

**Issue by joaociocca** [iRon7/Write-Log#3]
Maybe an implementation of something like is described on this link could be used?

https://stackoverflow.com/questions/8761888/capturing-standard-out-and-error-with-start-process

**Comment by iRon7** [comment]
`.StandardOutput` provides a string, this means that the solution will lose an important feature where it unravels (recursive) objects.  
If you want to use `stdout` on yourself for call a external command, I quest you can do something like: `Log Invoke-Expression "$command>&1"` or simply `Log $stdOutAndError` after your external command.

**Comment by iRon7** [comment]
Get Test Command
